*システム全体方針終わり*
ritscc/soukai-2022-2 pull request #91
Opened 2023-02-17 06:52 UTC by rintaro29

fix #42

2023-02-18 09:59 UTC, kyochn requested changes

2023-02-18 09:59 UTC, kyochn commented on src/houshin/system/01_zentai.tex
> +\subsubsction*{局内方針}
スペルミス
```suggestion
\subsubsection*{局内方針}
```

2023-02-18 10:32 UTC, rintaro29 commented on src/houshin/system/01_zentai.tex
> +\subsubsction*{局内方針}
修正しました

2023-02-22 05:48 UTC, minusno0708 approved these changes

2023-02-22 05:54 UTC, merged